server:
  port: 9090
---
spring:
  cloud:
    gateway:
      routes:
        - id: expense
          uri: http://localhost:9081/
          predicates:
            - Path=/expense/**
        - id: people
          uri: http://localhost:8081/
          predicates:
            - Path=/people/**